name: Manual workflow

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select the environment
        options:
        - DEV
        - SIT
        - PRD
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
      OAUTH2: https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token
      TOKEN: "token_access"
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify Client Credentials
      run: |
        token=$(curl -L -X POST $OAUTH2 -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "client_id=$CLIENT_ID" \
        --data-urlencode "client_secret=$CLIENT_SECRET" \
        --data-urlencode "grant_type=client_credentials" | ./jq.exe .'access_token')

        temp="${token%\"}"
        temp="${temp#\"}"
        echo "TOKEN=$temp" >> $GITHUB_ENV
        echo "AccessToken: $TOKEN"

#     - name: Clone mulesoft-scgp-api
#       uses: actions/checkout@v2
#       with:
#         repository: scg-wedo-dev-ex/mulesoft-scgp-api
#         token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT
#         path: ./mulesoft
#         ref: main
    
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'

    - name: Build package
      run: mvn -B package -DauthToken="$TOKEN" -s settings.xml
    
    - name: Deploy package
      run: ls target/*.jar
