name: Mulesoft Package

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
      OAUTH2: https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token
      ACCESS_TOKEN: "GENERATE_OAUTH2"
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify Client Credentials
      run: |
        echo "ACCESS_TOKEN=$(curl -sL -X POST $OAUTH2 -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "client_id=$CLIENT_ID" \
        --data-urlencode "client_secret=$CLIENT_SECRET" \
        --data-urlencode "grant_type=client_credentials" | jq .'access_token')" >> $GITHUB_ENV

#     - name: Clone mulesoft-scgp-api
#       uses: actions/checkout@v2
#       with:
#         repository: scg-wedo-dev-ex/mulesoft-scgp-api
#         token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT
#         path: ./mulesoft
#         ref: main
    
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup jdk8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'

    - name: Maven Settings
      uses: whelk-io/maven-settings-xml-action@v16
      with:
        repositories: |
              [
                {
                  "id": "MuleRepository",
                  "name": "MuleRepository",
                  "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/",
                  "releases": {
                    "enabled": "true"
                  },
                  "snapshots": {
                    "enabled": "true"
                  }
                }
              ]
        servers: |
              [
                {
                  "id": "anypoint-exchange-v2",
                  "username": "~~~Token~~~",
                  "password": ${{ env.ACCESS_TOKEN }},
                  "configuration": {
                    "httpConfiguration": {
                      "all": {
                        "usePreemptive": "true"
                      }
                    }
                  }
                },
                {
                  "id": "MuleRepository",
                  "username": "${{ secrets.ENT_ID }}",
                  "password": "${{ secrets.ENT_PASSWORD }}",
                  "configuration": {
                    "httpConfiguration": {
                      "all": {
                        "usePreemptive": "true"
                      }
                    }
                  }
                }
              ]      
        

    - name: Build package
      # run: mvn -B package -DauthToken=${{ env.ACCESS_TOKEN }} -s settings.xml
      run: mvn clean package
    
    - name: Deploy package
      run: ls target/*.jar
