name: Mulesoft Package

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
    steps:

    - name: Verify Client Credentials
      run: |
        curl -Lifs -X POST https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token \
        -H 'Content-Type: application/json' \
        -d '{"grant_type":"client_credentials","client_id":"${{ env.CLIENT_ID }}","client_secret":"${{ env.CLIENT_SECRET }}"}'

    - name: Checkout scdp-cicd-integation
      uses: actions/checkout@v2

    - name: Checkout mulesoft-scgp-api
      uses: actions/checkout@v2
      with:
        repository: dvgamerr/scgp-mule-domain
        path: ./mule-domain
        ref: main
    
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup jdk8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'

    - name: Build mule-domain
      run: |
        cd ./mule-domain
        mvn clean package install -f pom.xml

    - name: Deploy package
      run: ls target/*.jar
