name: Manual workflow

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select the environment
        options:
        - DEV
        - SIT
        - PRD
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
#     - name: Clone mulesoft-scgp-api
#       uses: actions/checkout@v2
#       with:
#         repository: scg-wedo-dev-ex/mulesoft-scgp-api
#         token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT
#         path: ./mulesoft
#         ref: main
    
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'

    - name: Build
      run: mvn -B deploy -DmuleDeploy -s settings.xml
    
    - name: Deploy package
      run: ls target/*.jar
