name: Manual Deploy Runtime Manager

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select the environment
        options:
        - DEV
        - SIT
        - PRD
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
      OAUTH2: https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token
      ACCESS_TOKEN: "GENERATE_OAUTH2"
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Verify Client Credentials
      run: |
        echo "ACCESS_TOKEN=$(curl -sL -X POST $OAUTH2 -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "client_id=$CLIENT_ID" \
        --data-urlencode "client_secret=$CLIENT_SECRET" \
        --data-urlencode "grant_type=client_credentials" | jq .'access_token')" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'

    - name: Build package
      run: mvn install
    
    - name: Deploy package
      run: ls target/*.jar
